const data = [
    {
      id: 1,
      name: "Jhon",
      story: "Ghostbusters",
      prompt: "A long time ago in a galaxy far, far away",
      upvote: 3,
    },
    {
      id: 2,
      name: "Jhon",
      story: "Inception",
      prompt: "Once in a lifetime",
      upvote: 2,
    },
    {
      id: 3,
      name: "Jhon",
      story: "Beetlejuice",
      prompt: "It was a dark and stormy night",
      upvote: 5,
    },
    {
      id: 4,
      name: "Jhon",
      story: "The Matrix",
      prompt: "In a galaxy far, far away",
      upvote: 1,
    },
    {
      id: 5,
      name: "Jhon",
      story: "Star Wars",
      prompt: "Once upon a time",
      upvote: 4,
    },
    {
      id: 6,
      name: "Jhon",
      story: "Inception",
      prompt: "A long time ago in a galaxy far, far away",
      upvote: 3,
    },
    {
      id: 7,
      name: "Jhon",
      story: "It was a dark and stormy night",
      prompt: "Ghostbusters",
      upvote: 2,
    },
    {
      id: 8,
      name: "Jhon",
      story: "Once upon a time",
      prompt: "Beetlejuice",
      upvote: 5,
    },
    {
      id: 9,
      name: "Jhon",
      story: "In a galaxy far, far away",
      prompt: "The Matrix",
      upvote: 1,
    },
    {
      id: 10,
      name: "Jhon",
      story: "A long time ago in a galaxy far, far away",
      prompt: "Star Wars",
      upvote: 4,
    },
    {
      id: 11,
      name: "Jhon",
      story: "Star Wars",
      prompt: "It was a dark and stormy night",
      upvote: 3,
    },
    {
      id: 12,
      name: "Jhon",
      story: "Once in a lifetime",
      prompt: "Inception",
      upvote: 2,
    },
    {
      id: 13,
      name: "Jhon",
      story: "Beetlejuice",
      prompt: "Once upon a time",
      upvote: 5,
    },
    {
      id: 14,
      name: "cooldude",
      story: "Ghostbusters",
      prompt: "A long time ago in a galaxy far, far away",
      upvote: 1,
    },
    {
      id: 15,
      name: "Jhon",
      story: "The Matrix",
      prompt: "In a galaxy far, far away",
      upvote: 4,
    },
    {
      id: 16,
      name: "Jhon",
      story: "It was a dark and stormy night",
      prompt: "Once in a lifetime",
      upvote: 3,
    },
    {
      id: 17,
      name: "Jhon",
      story: "Once upon a time",
      prompt: "Ghostbusters",
      upvote: 2,
    },
    {
      id: 18,
      name: "Jhon",
      story: "A long time ago in a galaxy far, far away",
      prompt: "Beetlejuice",
      upvote: 5,
    },
    {
      id: 19,
      name: "Jhon",
      story: "Star Wars",
      prompt: "It was a dark and stormy night",
      upvote: 1,
    },
    {
      id: 20,
      name: "Jhon",
      story: "Inception",
      prompt: "Once upon a time",
      upvote: 4,
    },
    {
      id: 21,
      name: "Jhon",
      story: "It was a dark and stormy night",
      prompt: "A long time ago in a galaxy far, far away",
      upvote: 3,
    },
    {
      id: 22,
      name: "Jhon",
      story: "Ghostbusters",
      prompt: "Once in a lifetime",
      upvote: 2,
    },
    {
      id: 23,
      name: "Jhon",
      story: "Once upon a time",
      prompt: "Ghostbusters",
      upvote: 5,
    },
    {
      id: 24,
      name: "Jhon",
      story: "Inception",
      prompt: "It was a dark and stormy night",
      upvote: 1,
    },
    {
      id: 25,
      name: "Jhon",
      story: "The Matrix",
      prompt: "A long time ago in a galaxy far, far away",
      upvote: 4,
    },
    {
      id: 26,
      name: "Jhon",
      story: "Beetlejuice",
      prompt: "Once upon a time",
      upvote: 3,
    },
    {
      id: 27,
      name: "Jhon",
      story: "In a galaxy far, far away",
      prompt: "It was a dark and stormy night",
      upvote: 2,
    },
    {
      id: 28,
      name: "Jhon",
      story: "Star Wars",
      prompt: "Once in a lifetime",
      upvote: 5,
    },
    {
      id: 29,
      name: "Jhon",
      story: "A long time ago in a galaxy far, far away",
      prompt: "Ghostbusters",
      upvote: 1,
    },
    {
      id: 30,
      name: "Jhon",
      story: "Once upon a time",
      prompt: "The Matrix",
      upvote: 4,
    },
  ];

  export default data;


