
const initial = [
    {
      productName: "Dell XPS 13",
      color: "Rose Gold",
      category: "Laptop",
      price: 1499,
    },
    {
      productName: "HP Spectre x360",
      color: "Dark Ash Silver",
      category: "Laptop",
      price: 1399,
    },
    {
      productName: "Logitech MX Master 3",
      color: "Graphite",
      category: "Accessories",
      price: 79,
    },
    {
      productName: "Samsung Galaxy Tab S7",
      color: "Mystic Bronze",
      category: "Tablet",
      price: 649,
    },
    {
      productName: "Sony WH-1000XM4",
      color: "Black",
      category: "Headphones",
      price: 349,
    },
    {
      productName: "Apple iPad Air",
      color: "Sky Blue",
      category: "Tablet",
      price: 599,
    },
    {
      productName: "Bose QuietComfort 35 II",
      color: "Silver",
      category: "Headphones",
      price: 299,
    },
    {
      productName: "Google Pixelbook Go",
      color: "Not Pink",
      category: "Laptop",
      price: 649,
    },
    {
      productName: "Razer DeathAdder Elite",
      color: "Chroma RGB",
      category: "Accessories",
      price: 69,
    },
    {
      productName: "Microsoft Surface Book 3",
      color: "Platinum",
      category: "Laptop",
      price: 2199,
    },
    {
        productName: "HP Envy x360",
        color: "Silver",
        category: "Laptop",
        price: 1099,
      },
      {
        productName: "Apple iPhone 13 Pro",
        color: "Graphite",
        category: "Smartphone",
        price: 1199,
      },
      {
        productName: "Samsung Galaxy Tab S7",
        color: "Mystic Bronze",
        category: "Tablet",
        price: 649,
      },
      {
        productName: "Bose QuietComfort 45",
        color: "Black",
        category: "Headphones",
        price: 349,
      },
      {
        productName: "Dell Ultrasharp 27",
        color: "InfinityEdge",
        category: "Monitor",
        price: 599,
      },
      {
        productName: "Logitech MX Master 4",
        color: "Graphite",
        category: "Accessories",
        price: 79,
      },
      {
        productName: "Sony Bravia 65-inch 4K TV",
        color: "Black",
        category: "TV",
        price: 1199,
      },
      {
        productName: "Microsoft Surface Laptop 4",
        color: "Platinum",
        category: "Laptop",
        price: 1299,
      },
      {
        productName: "Google Pixel 6 Pro",
        color: "Stormy Black",
        category: "Smartphone",
        price: 899,
      },
      {
        productName: "Lenovo Legion 7i",
        color: "Slate Grey",
        category: "Gaming Laptop",
        price: 1499,
      },
      {
        productName: "Sony WH-1000XM5",
        color: "Silver",
        category: "Headphones",
        price: 399,
      },
      {
        productName: "LG OLED C1 55-inch TV",
        color: "Cinematic Sound",
        category: "TV",
        price: 1499,
      },
      {
        productName: "Apple iPad Pro",
        color: "Space Gray",
        category: "Tablet",
        price: 799,
      },
      {
        productName: "Corsair K95 RGB Platinum XT",
        color: "Gunmetal",
        category: "Keyboard",
        price: 179,
      },
      {
        productName: "Razer Blade 15",
        color: "Mercury White",
        category: "Gaming Laptop",
        price: 1799,
      },
      {
        productName: "Samsung Odyssey G7",
        color: "Phantom Blue",
        category: "Monitor",
        price: 699,
      },
      {
        productName: "Apple Watch Series 7",
        color: "Midnight",
        category: "Wearable",
        price: 349,
      },
      {
        productName: "GoPro Hero 10",
        color: "Black",
        category: "Action Camera",
        price: 449,
      },
      {
        productName: "Bowers & Wilkins 606 S2",
        color: "White",
        category: "Speakers",
        price: 799,
      },
      {
        productName: "DJI Air 2S",
        color: "Obsidian Black",
        category: "Drone",
        price: 999,
      },
      {
        productName: "Dell XPS 13",
        color: "Rose Gold",
        category: "Laptop",
        price: 1499,
      },
      {
        productName: "HP Spectre x360",
        color: "Dark Ash Silver",
        category: "Laptop",
        price: 1399,
      },
      {
        productName: "Logitech MX Master 3",
        color: "Graphite",
        category: "Accessories",
        price: 79,
      },
      {
        productName: "Samsung Galaxy Tab S7",
        color: "Mystic Bronze",
        category: "Tablet",
        price: 649,
      },
      {
        productName: "Sony WH-1000XM4",
        color: "Black",
        category: "Headphones",
        price: 349,
      },
      {
        productName: "Apple iPad Air",
        color: "Sky Blue",
        category: "Tablet",
        price: 599,
      },
      {
        productName: "Bose QuietComfort 35 II",
        color: "Silver",
        category: "Headphones",
        price: 299,
      },
      {
        productName: "Google Pixelbook Go",
        color: "Not Pink",
        category: "Laptop",
        price: 649,
      },
      {
        productName: "Razer DeathAdder Elite",
        color: "Chroma RGB",
        category: "Accessories",
        price: 69,
      },
      {
        productName: "Microsoft Surface Book 3",
        color: "Platinum",
        category: "Laptop",
        price: 2199,
      },
      {
          productName: "HP Envy x360",
          color: "Silver",
          category: "Laptop",
          price: 1099,
        },
        {
          productName: "Apple iPhone 13 Pro",
          color: "Graphite",
          category: "Smartphone",
          price: 1199,
        },
        {
          productName: "Samsung Galaxy Tab S7",
          color: "Mystic Bronze",
          category: "Tablet",
          price: 649,
        },
        {
          productName: "Bose QuietComfort 45",
          color: "Black",
          category: "Headphones",
          price: 349,
        },
        {
          productName: "Dell Ultrasharp 27",
          color: "InfinityEdge",
          category: "Monitor",
          price: 599,
        },
        {
          productName: "Logitech MX Master 4",
          color: "Graphite",
          category: "Accessories",
          price: 79,
        },
        {
          productName: "Sony Bravia 65-inch 4K TV",
          color: "Black",
          category: "TV",
          price: 1199,
        },
        {
          productName: "Microsoft Surface Laptop 4",
          color: "Platinum",
          category: "Laptop",
          price: 1299,
        },
        {
          productName: "Google Pixel 6 Pro",
          color: "Stormy Black",
          category: "Smartphone",
          price: 899,
        },
        {
          productName: "Lenovo Legion 7i",
          color: "Slate Grey",
          category: "Gaming Laptop",
          price: 1499,
        },
        {
          productName: "Sony WH-1000XM5",
          color: "Silver",
          category: "Headphones",
          price: 399,
        },
        {
          productName: "LG OLED C1 55-inch TV",
          color: "Cinematic Sound",
          category: "TV",
          price: 1499,
        },
        {
          productName: "Apple iPad Pro",
          color: "Space Gray",
          category: "Tablet",
          price: 799,
        },
        {
          productName: "Corsair K95 RGB Platinum XT",
          color: "Gunmetal",
          category: "Keyboard",
          price: 179,
        },
        {
          productName: "Razer Blade 15",
          color: "Mercury White",
          category: "Gaming Laptop",
          price: 1799,
        },
        {
          productName: "Samsung Odyssey G7",
          color: "Phantom Blue",
          category: "Monitor",
          price: 699,
        },
        {
          productName: "Apple Watch Series 7",
          color: "Midnight",
          category: "Wearable",
          price: 349,
        },
        {
          productName: "GoPro Hero 10",
          color: "Black",
          category: "Action Camera",
          price: 449,
        },
        {
          productName: "Bowers & Wilkins 606 S2",
          color: "White",
          category: "Speakers",
          price: 799,
        },
        {
          productName: "DJI Air 2S",
          color: "Obsidian Black",
          category: "Drone",
          price: 999,
        },
      
  ];

  export default initial;